import Header from "@/components/Layout/Header";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "@/components/Layout/Footer";

const mazda = localFont({
  src: [
    {
      path: "../assets/fonts/mazdatypeviet-regular.woff",
      weight: "400",
      style: "regular",
    },
    {
      path: "../assets/fonts/mazdatypeviet-medium.woff",
      weight: "500",
      style: "medium",
    },
    {
      path: "../assets/fonts/mazdatypeviet-bold.woff",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className={mazda.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
