import Header from "@/components/Layout/Header";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "@/components/Layout/Footer";
import StickyBtns from "@/components/Layout/StickyBtns";
import MobileBottomNav from "@/components/Layout/MobileBottomNav";
import StyledProgressBar from "@/components/ProgressBar";

const mazda = localFont({
  src: [
    {
      path: "../assets/fonts/mazdatypeviet-regular.woff",
      weight: "400",
      style: "regular",
    },
    {
      path: "../assets/fonts/mazdatypeviet-medium.woff",
      weight: "500",
      style: "medium",
    },
    {
      path: "../assets/fonts/mazdatypeviet-bold.woff",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="vi">
        <body className={mazda.className}>
          <StyledProgressBar />
          <Header />
          {children}
          <Footer />
          <StickyBtns />
          <MobileBottomNav />
        </body>
      </html>
    </>
  );
}
